[preload  storage="./data/bgimage/bg_base.png"  ]
[preload  storage="./data/fgimage/default/item/naginata-removebg-preview.png"  ]
[preload  storage="./data/fgimage/default/item/sword-removebg-preview.png"  ]
[preload  storage="./data/fgimage/default/item/2.png"  ]
[preload  storage="./data/fgimage/default/item/1.png"  ]
[return] 